[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.idea
  | \.env
  | \.venv
  | \.vscode
  | \.pytest_cache
  | docs
	| __pycache__
  | data
  | docs
  | static
)/
'''