version: "3"

tasks:
  init:
    desc: "Установка зависимостей"
    cmds:
      - pip install -r requirements.txt

  test:
    desc: "Запуск всех тестов"
    cmds:
      - PYTHONPATH=src pytest tests

  server:
    desc: "Запуск HTTP-сервера"
    cmds:
      - cd src && PYTHONPATH=src python3 main.py

  format:
    desc: "Форматирование кода с помощью black"
    cmds:
      - black .

  lint:
    desc: "Проверка кода через flake8"
    cmds:
      - flake8 src/ tests/

  all:
    desc: "Выполнить всё: lint + test"
    deps: [lint, test]
