name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/27017 || exit 1'"
          --health-interval 10s
          --health-timeout 15s
          --health-retries 10

    steps:
      # 1. Скачиваем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запуск линтера
      - name: Run linter
        run: |
          flake8 .

      # 5. Тесты через pytest
      - name: Run tests
        run: |
          PYTHONPATH=src pytest tests
